ML_config:
  model_args:
    num_classes: 10
  train_config:
    epochs: 3
    lr: 0.0001
    train_bs: 16
  test_config:
    test_bs: 16
  initial_model_path: initial_models
  dataset_dir: /home/acm-ws-darts/fedml/CIFAR10_dirichlet0.05_12
  dataset_id: CIFAR10_dirichlet0.05_12
  model_file_path: models/CNN_custom.py
  model_id: CNN_custom

FL_config:
  Agg_algo: fedavg
  Agg_args: None
  CS_algo: fedbandits
  CS_args:
    bandit_algo: ucb  # Options: ucb, ts, exp3
    epsilon: 0.1
    initial_random_rounds: 5
    exploration_param: 1.414
  clients_per_round: 3
  total_num_clients: 12
  total_rounds: 20

client_config:
  minibatch_time: 0.1293

server_config:
  test_bs: 16
  seed: 1201
  use_gpu: false
  save_path: ../results